{{- if not .Values.garmin.existingSecret }}
{{- if not .Values.garmin.username }}
  {{- fail "garmin.username is required when garmin.existingSecret is not set" }}
{{- end }}
{{- if not .Values.garmin.password }}
  {{- fail "garmin.password is required when garmin.existingSecret is not set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-withings-sync.fullname" . }}
  labels:
    {{- include "docker-withings-sync.labels" . | nindent 4 }}
type: Opaque
data:
  GARMIN_USERNAME: {{ .Values.garmin.username | b64enc | quote }}
  GARMIN_PASSWORD: {{ .Values.garmin.password | b64enc | quote }}
{{- end }}
