{{- if not .Values.garmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-withings-sync.fullname" . }}
  labels:
    {{- include "docker-withings-sync.labels" . | nindent 4 }}
type: Opaque
data:
  GARMIN_USERNAME: {{ .Values.garmin.username | b64enc | quote }}
  GARMIN_PASSWORD: {{ .Values.garmin.password | b64enc | quote }}
{{- end }}
